//Just a bunch of defines that will represent gameRules

#define START_INCOME 100
#define START_POPULATION 50
#define POPUL_INCOME_RATIO 2
#define START_MONEY 1000
#define START_FOOD 200
#define START_DEF_BONUS 20
#define MAX_CASTLES 10
#define MOVESPEED_LORD 100
#define MOVESPEED_ARCHER 60
#define MOVESPEED_HORSEMEN 90
#define MOVESPEED_SWORDSMEN 40
#define MOVESPEED_SPEARMEN 50
//building things
#define HOUSE_POPULATION_INC 10
#define SHOP_INCOME_INC 10
#define FARM_FOOD_INC 10
#define TOWER_DEF_BONUS_INC 10
#define MARKET_INCOME_INC 100
#define STONE_WALL_DEF_BONUS_INC 100
